# fly.toml app configuration file generated for frontend-winter-violet-9303 on 2024-08-14T23:36:28+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-winter-violet-9303'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
