# fly.toml app configuration file generated for frontend-utility-ai on 2024-08-12T03:21:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-utility-ai'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  cmd = ["vite", "build"]

[[statics]]
  guest_path = "/public"
  url_prefix = "/"
  [[statics.routes]]
  match = "/*"
  file = "index.html"
